import clock from "@/assets/p-clock.jpg";
import woodart from "@/assets/p-woodart.jpg";
import frame from "@/assets/p-frame.jpg";
import poster from "@/assets/p-poster.jpg";
import canvas from "@/assets/p-canvas.jpg";
import sculpture from "@/assets/p-sculpture.jpg";
import vase from "@/assets/p-vase.jpg";
import planter from "@/assets/p-planter.jpg";
import mirror from "@/assets/p-mirror.jpg";
import lamp from "@/assets/p-lamp.jpg";
import candle from "@/assets/p-candle.jpg";
import showpiece from "@/assets/p-showpiece.jpg";
import dreamcatcher from "@/assets/p-dreamcatcher.jpg";
import tray from "@/assets/p-tray.jpg";
import resin from "@/assets/p-resin.jpg";
import roomLiving from "@/assets/hero-living.jpg";
import roomBedroom from "@/assets/room-bedroom.jpg";
import bannerStatement from "@/assets/banner-statement.jpg";

export const IMAGES: Record<string, string> = {
  img1: "/Images/WhatsApp Image 2026-09-10 at 16.28.46 (1).webp",
  img2: "/Images/WhatsApp Image 2026-09-10 at 16.28.46 (2).webp",
  img3: "/Images/WhatsApp Image 2026-09-10 at 16.28.46.webp",
  img4: "/Images/WhatsApp Image 2026-09-10 at 16.28.47 (1).webp",
  img5: "/Images/WhatsApp Image 2026-09-10 at 16.28.47.webp",
  img6: "/Images/WhatsApp Image 2026-09-10 at 16.28.48 (1).webp",
  img7: "/Images/WhatsApp Image 2026-09-10 at 16.28.48 (2).webp",
  img8: "/Images/WhatsApp Image 2026-09-10 at 16.28.48.webp",
  img9: "/Images/WhatsApp Image 2026-09-10 at 16.28.49 (1).webp",
  img10: "/Images/WhatsApp Image 2026-09-10 at 16.28.49.webp",
  img11: "/Images/WhatsApp Image 2026-09-10 at 16.28.50 (1).webp",
  img12: "/Images/WhatsApp Image 2026-09-10 at 16.28.50.webp",
  img13: "/Images/WhatsApp Image 2026-09-10 at 16.28.51.webp",
  img14: "/Images/WhatsApp Image 2026-09-10 at 16.28.52.webp",
  img15: "/Images/WhatsApp Image 2026-09-10 at 16.29.02.webp",

  clock,
  woodart,
  frame,
  poster,
  canvas,
  sculpture,
  vase,
  planter,
  mirror,
  lamp,
  candle,
  showpiece,
  dreamcatcher,
  tray,
  resin,
  roomLiving,
  roomBedroom,
  bannerStatement,
};

export type ImageKey = keyof typeof IMAGES;

export type Product = {
  id: string;
  slug: string;
  name: string;
  category: string; // category slug
  subcategory: string;
  price: number;
  mrp: number;
  rating: number;
  reviews: number;
  image: string;
  gallery: string[];
  style: string;
  room: string[];
  material: string;
  color: string;
  size: string;
  dimensions: string;
  weight: string;
  stock: number;
  badges: ("bestseller" | "new" | "featured")[];
  description: string;
  care: string;
};

export type Category = {
  slug: string;
  name: string;
  image: string;
  group: string;
  blurb: string;
};

export const CATEGORIES: Category[] = [
  {
    slug: "wall-clocks",
    name: "Wall Clocks",
    image: "clock",
    group: "Wall Décor",
    blurb: "Quiet time, beautifully told.",
  },
  {
    slug: "wall-decor",
    name: "Wall Décor",
    image: "woodart",
    group: "Wall Décor",
    blurb: "Carved wood, texture and warmth.",
  },
  {
    slug: "frames",
    name: "Frames",
    image: "frame",
    group: "Wall Décor",
    blurb: "Hold your memories in good taste.",
  },
  {
    slug: "posters",
    name: "Posters",
    image: "poster",
    group: "Wall Décor",
    blurb: "Botanical calm for empty walls.",
  },
  {
    slug: "canvas-art",
    name: "Canvas Art",
    image: "canvas",
    group: "Art",
    blurb: "Brushstrokes that anchor a room.",
  },
  {
    slug: "abstract-art",
    name: "Abstract Art",
    image: "resin",
    group: "Art",
    blurb: "Movement, gold and quiet drama.",
  },
  {
    slug: "stone-art",
    name: "Stone Art",
    image: "sculpture",
    group: "Art",
    blurb: "Hand-finished marble and sandstone.",
  },
  {
    slug: "sculptures",
    name: "Sculptures",
    image: "showpiece",
    group: "Art",
    blurb: "Sculptural pieces with presence.",
  },
  {
    slug: "vases",
    name: "Vases",
    image: "vase",
    group: "Living Room",
    blurb: "Ceramic silhouettes for stems.",
  },
  {
    slug: "showpieces",
    name: "Showpieces",
    image: "showpiece",
    group: "Living Room",
    blurb: "Small objects, big impact.",
  },
  {
    slug: "plants-planters",
    name: "Plants & Planters",
    image: "planter",
    group: "Living Room",
    blurb: "Evergreen greens, zero upkeep.",
  },
  {
    slug: "mirrors",
    name: "Mirrors",
    image: "mirror",
    group: "Wall Décor",
    blurb: "Light, doubled.",
  },
];

export const NAV_GROUPS: { title: string; items: { name: string; slug: string }[] }[] = [
  {
    title: "Wall Décor",
    items: [
      { name: "Wall Clocks", slug: "wall-clocks" },
      { name: "Posters", slug: "posters" },
      { name: "Frames", slug: "frames" },
      { name: "Canvas Art", slug: "canvas-art" },
      { name: "Mirrors", slug: "mirrors" },
    ],
  },
  {
    title: "Art",
    items: [
      { name: "Abstract Art", slug: "abstract-art" },
      { name: "Stone Art", slug: "stone-art" },
      { name: "Sculptures", slug: "sculptures" },
      { name: "Canvas Art", slug: "canvas-art" },
      { name: "Wall Décor", slug: "wall-decor" },
    ],
  },
  {
    title: "Living Room",
    items: [
      { name: "Showpieces", slug: "showpieces" },
      { name: "Vases", slug: "vases" },
      { name: "Plants & Planters", slug: "plants-planters" },
      { name: "Mirrors", slug: "mirrors" },
    ],
  },
  {
    title: "Bedroom",
    items: [
      { name: "Wall Décor", slug: "wall-decor" },
    ],
  },
  {
    title: "Gifts",
    items: [
      { name: "Under ₹999", slug: "under-999" },
      { name: "Housewarming", slug: "new-home" },
      { name: "Festive Gifts", slug: "gift-ideas" },
      { name: "Statement Pieces", slug: "statement-pieces" },
    ],
  },
];

export const STYLES = [
  { name: "Minimalist", tag: "minimalist", line: "Less clutter. More character." },
  { name: "Modern", tag: "modern", line: "Clean lines with a confident edge." },
  { name: "Boho", tag: "boho", line: "Warm textures and effortless charm." },
  { name: "Vintage", tag: "vintage", line: "Pieces that carry a little history." },
  { name: "Luxury", tag: "luxury", line: "Marble, brass and quiet richness." },
  { name: "Scandinavian", tag: "scandinavian", line: "Pale wood, soft light, calm." },
  { name: "Rustic", tag: "rustic", line: "Raw grain and honest finishes." },
  { name: "Contemporary", tag: "contemporary", line: "Today's shapes, timeless palette." },
];

export const ROOMS = [
  { name: "Living Room", slug: "living-room", image: "roomLiving" as ImageKey },
  { name: "Bedroom", slug: "bedroom", image: "roomBedroom" as ImageKey },
  { name: "Dining Room", slug: "dining-room", image: "tray" as ImageKey },
  { name: "Entryway", slug: "entryway", image: "bannerStatement" as ImageKey },
  { name: "Home Office", slug: "home-office", image: "woodart" as ImageKey },
  { name: "Balcony", slug: "balcony", image: "planter" as ImageKey },
  { name: "Bathroom", slug: "bathroom", image: "mirror" as ImageKey },
];

export const COLLECTIONS = [
  { slug: "under-999", title: "Under ₹999", blurb: "Beautiful things that cost little." },
  { slug: "luxury-decor", title: "Luxury Décor", blurb: "Marble, brass and hand-finished stone." },
  { slug: "minimalist", title: "Minimalist Collection", blurb: "Calm shapes, quiet palettes." },
  { slug: "new-home", title: "New Home Collection", blurb: "Everything a fresh space needs." },
  { slug: "trending-now", title: "Trending Now", blurb: "What our customers are loving." },
  { slug: "gift-ideas", title: "Gift Ideas", blurb: "Thoughtful décor for every occasion." },
  { slug: "statement-pieces", title: "Statement Pieces", blurb: "One object, whole-room impact." },
  { slug: "small-decor", title: "Small Décor, Big Impact", blurb: "Little accents, styled well." },
];

const slugify = (s: string) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");

type Seed = Omit<Product, "id" | "slug" | "gallery"> & { gallery?: ImageKey[] };

const seeds: Seed[] = [
  {
    name: "Minimalist Wooden Wall Clock",
    category: "wall-clocks",
    subcategory: "Silent Clocks",
    price: 269,
    mrp: 2499,
    rating: 4.7,
    reviews: 218,
    image: "img6",
    style: "minimalist",
    room: ["living-room", "home-office"],
    material: "Seasoned Sheesham Wood",
    color: "Natural Oak",
    size: "Medium",
    dimensions: "30 x 30 x 4 cm",
    weight: "1.1 kg",
    stock: 24,
    badges: ["bestseller", "featured"],
    description:
      "A pared-back dial in seasoned wood with a whisper-quiet sweep movement — designed to read the hour without shouting for attention.",
    care: "Wipe with a dry, soft cloth. Keep away from direct moisture.",
  },
  {
    name: "Walnut Roman Numeral Clock",
    category: "wall-clocks",
    subcategory: "Statement Clocks",
    price: 279,
    mrp: 3499,
    rating: 4.6,
    reviews: 132,
    image: "img12",
    style: "vintage",
    room: ["living-room"],
    material: "Walnut Finish MDF",
    color: "Deep Walnut",
    size: "Large",
    dimensions: "40 x 40 x 5 cm",
    weight: "1.6 kg",
    stock: 12,
    badges: ["featured"],
    description:
      "Slim brass hands over a warm walnut face, finished by hand for an heirloom feel above the console.",
    care: "Dust gently. Avoid abrasive cleaners.",
  },
  {
    name: "Brass Accent Skeleton Clock",
    category: "wall-clocks",
    subcategory: "Luxury Clocks",
    price: 289,
    mrp: 5999,
    rating: 4.8,
    reviews: 76,
    image: "img11",
    style: "luxury",
    room: ["living-room", "entryway"],
    material: "Metal & Brass Plating",
    color: "Antique Brass",
    size: "Large",
    dimensions: "50 x 50 x 5 cm",
    weight: "2.4 kg",
    stock: 8,
    badges: ["new"],
    description:
      "An open-frame dial ringed in antique brass — sculptural enough to work as wall art on its own.",
    care: "Polish with a dry microfibre cloth.",
  },
  {
    name: "Carved Wooden Wall Art Panel",
    category: "wall-decor",
    subcategory: "Wood Panels",
    price: 299,
    mrp: 4199,
    rating: 4.7,
    reviews: 164,
    image: "img2",
    style: "rustic",
    room: ["living-room", "bedroom"],
    material: "Mango Wood",
    color: "Warm Brown",
    size: "Large",
    dimensions: "60 x 60 x 4 cm",
    weight: "3.2 kg",
    stock: 15,
    badges: ["bestseller"],
    description:
      "Hand-carved leaf relief set into a geometric grid — the kind of piece that gives a plain wall texture and shadow.",
    care: "Dust weekly. Do not wash.",
  },
  {
    name: "Rustic Wooden Photo Frame Set",
    category: "wall-decor",
    subcategory: "Photo Frames",
    price: 259,
    mrp: 1499,
    rating: 4.4,
    reviews: 306,
    image: "img8",
    style: "rustic",
    room: ["living-room", "home-office"],
    material: "Pine Wood",
    color: "Driftwood Grey",
    size: "Set of 2 (5x7 in)",
    dimensions: "20 x 25 x 2 cm",
    weight: "0.8 kg",
    stock: 40,
    badges: ["bestseller"],
    description:
      "Softly distressed pine frames with ivory mats — table-top or wall, they flatter every photograph.",
    care: "Clean glass with a dry cloth.",
  },
  {
    name: "Oak Gallery Frame Trio",
    category: "frames",
    subcategory: "Gallery Frames",
    price: 269,
    mrp: 1999,
    rating: 4.6,
    reviews: 187,
    image: "frame",
    style: "minimalist",
    room: ["home-office", "living-room"],
    material: "Solid Oak",
    color: "Light Oak",
    size: "Set of 3 (A4)",
    dimensions: "21 x 30 cm each",
    weight: "1.4 kg",
    stock: 30,
    badges: [],
    description: "Three slim oak frames sized for A4 prints — the easiest way to start a gallery wall.",
    care: "Wipe with a dry cloth.",
  },
  {
    name: "Beige Botanical Poster",
    category: "posters",
    subcategory: "Botanical Prints",
    price: 279,
    mrp: 1299,
    rating: 4.5,
    reviews: 241,
    image: "poster",
    style: "minimalist",
    room: ["bedroom", "home-office"],
    material: "300 GSM Matte Art Paper",
    color: "Beige & Ivory",
    size: "A3 Framed",
    dimensions: "30 x 42 cm",
    weight: "0.9 kg",
    stock: 50,
    badges: ["bestseller", "featured"],
    description:
      "Fine line botanicals printed on heavyweight matte paper and framed in light oak — quiet, warm, endlessly wearable.",
    care: "Keep out of direct sunlight.",
  },
  {
    name: "Typography Art Print — Home",
    category: "posters",
    subcategory: "Typography Art",
    price: 289,
    mrp: 1399,
    rating: 4.3,
    reviews: 121,
    image: "img15",
    style: "contemporary",
    room: ["entryway", "living-room"],
    material: "Matte Art Paper",
    color: "Sand",
    size: "A3 Framed",
    dimensions: "30 x 42 cm",
    weight: "0.9 kg",
    stock: 35,
    badges: ["new"],
    description: "A single word, generously spaced — understated typography for an entryway wall.",
    care: "Dust the glass gently.",
  },
  {
    name: "Terracotta Abstract Canvas",
    category: "canvas-art",
    subcategory: "Abstract Canvas",
    price: 299,
    mrp: 6999,
    rating: 4.8,
    reviews: 143,
    image: "canvas",
    style: "modern",
    room: ["living-room"],
    material: "Cotton Canvas, Wooden Frame",
    color: "Terracotta & Sage",
    size: "Extra Large",
    dimensions: "90 x 120 x 4 cm",
    weight: "5.1 kg",
    stock: 6,
    badges: ["bestseller", "featured"],
    description:
      "Broad terracotta and sage strokes on gallery-wrapped cotton canvas — a room's whole colour story in one piece.",
    care: "Dust lightly. Never use water.",
  },
  {
    name: "Muted Landscape Canvas",
    category: "canvas-art",
    subcategory: "Landscape Canvas",
    price: 259,
    mrp: 4499,
    rating: 4.4,
    reviews: 87,
    image: "canvas",
    style: "contemporary",
    room: ["bedroom", "home-office"],
    material: "Cotton Canvas",
    color: "Sand & Grey",
    size: "Large",
    dimensions: "60 x 90 x 4 cm",
    weight: "3.2 kg",
    stock: 14,
    badges: [],
    description: "A hazy horizon in muted neutrals, stretched over a kiln-dried frame.",
    care: "Dust with a soft brush.",
  },
  {
    name: "Golden Swirl Resin Wall Art",
    category: "abstract-art",
    subcategory: "Resin Art",
    price: 269,
    mrp: 4999,
    rating: 4.7,
    reviews: 112,
    image: "img1",
    style: "luxury",
    room: ["living-room", "entryway"],
    material: "Epoxy Resin on MDF",
    color: "Ivory & Gold",
    size: "Medium",
    dimensions: "45 x 45 x 3 cm",
    weight: "2.8 kg",
    stock: 9,
    badges: ["new", "featured"],
    description:
      "Poured resin marbling with real gold leaf veins — every panel sets differently, so no two are alike.",
    care: "Wipe with a damp cloth; avoid solvents.",
  },
  {
    name: "Ivory Marble Effect Resin Panel",
    category: "abstract-art",
    subcategory: "Resin Art",
    price: 279,
    mrp: 3899,
    rating: 4.5,
    reviews: 64,
    image: "resin",
    style: "modern",
    room: ["bedroom"],
    material: "Epoxy Resin",
    color: "Ivory",
    size: "Small",
    dimensions: "30 x 30 x 3 cm",
    weight: "1.6 kg",
    stock: 18,
    badges: [],
    description: "Soft ivory marbling with a high-gloss finish, sized for a narrow wall or shelf lean.",
    care: "Avoid prolonged direct sun.",
  },
  {
    name: "Abstract Stone Sculpture",
    category: "sculptures",
    subcategory: "Marble Sculpture",
    price: 289,
    mrp: 7999,
    rating: 4.9,
    reviews: 58,
    image: "sculpture",
    style: "luxury",
    room: ["living-room", "entryway"],
    material: "Hand-carved Marble & Sandstone",
    color: "White & Sand",
    size: "Medium",
    dimensions: "22 x 14 x 30 cm",
    weight: "4.8 kg",
    stock: 5,
    badges: ["bestseller", "featured"],
    description:
      "Two stones in conversation — one polished marble arc, one raw sandstone base, finished entirely by hand.",
    care: "Dust with a dry cloth. Lift from the base.",
  },
  {
    name: "Sandstone Arch Object",
    category: "sculptures",
    subcategory: "Stone Objects",
    price: 299,
    mrp: 3299,
    rating: 4.4,
    reviews: 44,
    image: "sculpture",
    style: "minimalist",
    room: ["home-office", "living-room"],
    material: "Sandstone",
    color: "Sand",
    size: "Small",
    dimensions: "14 x 8 x 18 cm",
    weight: "1.9 kg",
    stock: 16,
    badges: [],
    description: "A small carved arch that adds quiet weight to a bookshelf or console.",
    care: "Dust only.",
  },
  {
    name: "Marble Finish Twist Showpiece",
    category: "sculptures",
    subcategory: "Table Sculpture",
    price: 259,
    mrp: 3999,
    rating: 4.6,
    reviews: 129,
    image: "showpiece",
    style: "luxury",
    room: ["living-room", "entryway"],
    material: "Resin with Marble Finish",
    color: "White & Gold",
    size: "Medium",
    dimensions: "12 x 12 x 26 cm",
    weight: "1.4 kg",
    stock: 20,
    badges: ["bestseller"],
    description:
      "A twisting marble-effect form banded in gold — glossy, sculptural and surprisingly light.",
    care: "Wipe with a soft dry cloth.",
  },
  {
    name: "Bronze Figurine Duo",
    category: "sculptures",
    subcategory: "Figurines",
    price: 269,
    mrp: 4799,
    rating: 4.5,
    reviews: 71,
    image: "bannerStatement",
    style: "vintage",
    room: ["entryway", "living-room"],
    material: "Polyresin, Bronze Finish",
    color: "Antique Bronze",
    size: "Set of 2",
    dimensions: "16 x 10 x 28 cm",
    weight: "2.6 kg",
    stock: 11,
    badges: ["featured"],
    description: "A pair of antique-bronze figures with beautifully aged patina for a console tableau.",
    care: "Dust gently; do not wash.",
  },
  {
    name: "Contemporary Table Vase",
    category: "wall-decor",
    subcategory: "Ceramic Vases",
    price: 279,
    mrp: 1899,
    rating: 4.6,
    reviews: 264,
    image: "img13",
    style: "minimalist",
    room: ["living-room", "dining-room"],
    material: "Glazed Ceramic",
    color: "Ivory",
    size: "Medium",
    dimensions: "14 x 14 x 24 cm",
    weight: "1.2 kg",
    stock: 38,
    badges: ["bestseller", "featured"],
    description:
      "A rounded ceramic silhouette with a soft ivory glaze — beautiful bare, better with pampas.",
    care: "Hand wash. Not dishwasher safe.",
  },
  {
    name: "Speckled Stoneware Bud Vase",
    category: "showpieces",
    subcategory: "Bud Vases",
    price: 289,
    mrp: 999,
    rating: 4.3,
    reviews: 178,
    image: "tray",
    style: "scandinavian",
    room: ["dining-room", "bedroom"],
    material: "Stoneware",
    color: "Speckled Grey",
    size: "Small",
    dimensions: "8 x 8 x 14 cm",
    weight: "0.5 kg",
    stock: 45,
    badges: [],
    description: "A palm-sized bud vase with a speckled matte body for single stems.",
    care: "Rinse by hand.",
  },
  {
    name: "Tall Fluted Floor Vase",
    category: "vases",
    subcategory: "Floor Vases",
    price: 299,
    mrp: 5299,
    rating: 4.7,
    reviews: 52,
    image: "vase",
    style: "modern",
    room: ["living-room", "entryway"],
    material: "Ceramic",
    color: "Cream",
    size: "Extra Large",
    dimensions: "24 x 24 x 55 cm",
    weight: "4.2 kg",
    stock: 7,
    badges: ["new"],
    description: "A fluted floor vase built for dramatic dried arrangements beside a sofa.",
    care: "Wipe clean; use a liner for water.",
  },
  {
    name: "Modern Ceramic Planter",
    category: "plants-planters",
    subcategory: "Planters",
    price: 259,
    mrp: 1699,
    rating: 4.5,
    reviews: 209,
    image: "planter",
    style: "contemporary",
    room: ["balcony", "living-room"],
    material: "Ceramic with Drainage",
    color: "Speckled Ivory",
    size: "Medium",
    dimensions: "18 x 18 x 18 cm",
    weight: "1.5 kg",
    stock: 33,
    badges: ["bestseller"],
    description: "A speckled ivory planter with a sand-toned foot and proper drainage hole.",
    care: "Use a saucer indoors.",
  },
  {
    name: "Artificial Monstera in Pot",
    category: "plants-planters",
    subcategory: "Artificial Plants",
    price: 269,
    mrp: 2799,
    rating: 4.4,
    reviews: 156,
    image: "planter",
    style: "boho",
    room: ["living-room", "home-office"],
    material: "Silk Leaf, Ceramic Pot",
    color: "Green & Ivory",
    size: "Large",
    dimensions: "40 x 40 x 70 cm",
    weight: "2.1 kg",
    stock: 22,
    badges: ["featured"],
    description: "Lifelike monstera leaves in a ceramic pot — all of the green, none of the watering.",
    care: "Dust leaves with a damp cloth.",
  },
  {
    name: "Arched Brass Wall Mirror",
    category: "mirrors",
    subcategory: "Arch Mirrors",
    price: 279,
    mrp: 8999,
    rating: 4.8,
    reviews: 94,
    image: "mirror",
    style: "luxury",
    room: ["entryway", "bathroom"],
    material: "Metal Frame, 5mm Mirror",
    color: "Brushed Brass",
    size: "Large",
    dimensions: "60 x 90 x 3 cm",
    weight: "7.4 kg",
    stock: 6,
    badges: ["bestseller", "featured"],
    description:
      "A slim brass arch that bounces daylight down a hallway and makes small rooms breathe.",
    care: "Clean with a lint-free cloth.",
  },
  {
    name: "Round Minimal Vanity Mirror",
    category: "mirrors",
    subcategory: "Round Mirrors",
    price: 289,
    mrp: 3799,
    rating: 4.5,
    reviews: 118,
    image: "mirror",
    style: "minimalist",
    room: ["bathroom", "bedroom"],
    material: "Metal Frame",
    color: "Matte Champagne",
    size: "Medium",
    dimensions: "50 x 50 x 3 cm",
    weight: "3.9 kg",
    stock: 19,
    badges: [],
    description: "A perfectly plain circle with a hairline frame — quiet above a basin or dresser.",
    care: "Avoid ammonia-based cleaners.",
  },
  {
    name: "Linen Shade Table Lamp",
    category: "showpieces",
    subcategory: "Table Lamps",
    price: 299,
    mrp: 3399,
    rating: 4.6,
    reviews: 174,
    image: "lamp",
    style: "contemporary",
    room: ["bedroom", "living-room"],
    material: "Ceramic Base, Linen Shade",
    color: "Ivory & Brass",
    size: "Medium",
    dimensions: "28 x 28 x 46 cm",
    weight: "2.3 kg",
    stock: 21,
    badges: ["bestseller"],
    description:
      "A glazed ceramic base with a brass collar and textured linen shade — the warmest light in the room.",
    care: "Unplug before wiping the base.",
  },
  {
    name: "Brass Cylinder Bedside Lamp",
    category: "showpieces",
    subcategory: "Bedside Lamps",
    price: 259,
    mrp: 2299,
    rating: 4.4,
    reviews: 96,
    image: "roomBedroom",
    style: "modern",
    room: ["bedroom"],
    material: "Metal & Fabric",
    color: "Brass",
    size: "Small",
    dimensions: "12 x 12 x 24 cm",
    weight: "0.9 kg",
    stock: 27,
    badges: ["new"],
    description: "A compact cylinder that throws soft light exactly where a bedside table needs it.",
    care: "Dust the shade with a brush.",
  },
  {
    name: "Ivory Pillar Candle Set with Brass Holders",
    category: "showpieces",
    subcategory: "Candle Sets",
    price: 269,
    mrp: 1999,
    rating: 4.7,
    reviews: 231,
    image: "candle",
    style: "luxury",
    room: ["dining-room", "bedroom"],
    material: "Soy Wax, Solid Brass",
    color: "Ivory & Brass",
    size: "Set of 3",
    dimensions: "Holders 9 cm dia",
    weight: "1.7 kg",
    stock: 29,
    badges: ["bestseller", "featured"],
    description:
      "Three unscented soy pillars on turned brass plates — a five-minute way to make dinner feel considered.",
    care: "Trim wick to 5 mm before lighting.",
  },
  {
    name: "Brass Taper Candle Holders",
    category: "showpieces",
    subcategory: "Candle Holders",
    price: 279,
    mrp: 1599,
    rating: 4.5,
    reviews: 141,
    image: "tray",
    style: "vintage",
    room: ["dining-room"],
    material: "Solid Brass",
    color: "Antique Brass",
    size: "Set of 2",
    dimensions: "7 x 7 x 12 cm",
    weight: "0.8 kg",
    stock: 24,
    badges: [],
    description: "Weighted brass holders for slim tapers, aged to a soft antique tone.",
    care: "Polish occasionally with brass cleaner.",
  },
  {
    name: "Wooden Serving Tray with Brass Handles",
    category: "showpieces",
    subcategory: "Trays",
    price: 289,
    mrp: 2599,
    rating: 4.6,
    reviews: 163,
    image: "tray",
    style: "rustic",
    room: ["living-room", "dining-room"],
    material: "Acacia Wood, Brass",
    color: "Natural & Brass",
    size: "Large",
    dimensions: "45 x 30 x 5 cm",
    weight: "1.8 kg",
    stock: 26,
    badges: ["bestseller"],
    description:
      "A generous acacia tray with brass handles — the styling shortcut every coffee table needs.",
    care: "Oil occasionally. Do not soak.",
  },
  {
    name: "Marble Centerpiece Bowl",
    category: "wall-decor",
    subcategory: "Centerpieces",
    price: 299,
    mrp: 4299,
    rating: 4.5,
    reviews: 68,
    image: "img14",
    style: "luxury",
    room: ["dining-room"],
    material: "Natural Marble",
    color: "White Marble",
    size: "Medium",
    dimensions: "26 x 26 x 8 cm",
    weight: "3.4 kg",
    stock: 12,
    badges: ["featured"],
    description: "A shallow marble bowl for fruit, keys or nothing at all.",
    care: "Wipe with a damp cloth; blot spills quickly.",
  },
  {
    name: "Macrame Dream Catcher",
    category: "wall-decor",
    subcategory: "Dream Catchers",
    price: 259,
    mrp: 1499,
    rating: 4.4,
    reviews: 197,
    image: "img5",
    style: "boho",
    room: ["bedroom"],
    material: "Cotton Cord, Natural Feathers",
    color: "Ivory & Tan",
    size: "Medium",
    dimensions: "25 x 70 cm",
    weight: "0.3 kg",
    stock: 41,
    badges: ["bestseller"],
    description: "Hand-knotted cotton with a woven sunburst centre and soft feather tails.",
    care: "Shake gently to dust.",
  },
  {
    name: "Woven Cotton Wall Hanging",
    category: "wall-decor",
    subcategory: "Macrame",
    price: 269,
    mrp: 2199,
    rating: 4.3,
    reviews: 84,
    image: "img4",
    style: "boho",
    room: ["living-room", "bedroom"],
    material: "Cotton Cord, Wooden Dowel",
    color: "Natural",
    size: "Large",
    dimensions: "60 x 90 cm",
    weight: "0.7 kg",
    stock: 17,
    badges: ["new"],
    description: "A large macrame panel with layered fringe that softens hard walls beautifully.",
    care: "Spot clean only.",
  },
  {
    name: "Marble & Gold Bookend Pair",
    category: "sculptures",
    subcategory: "Bookends",
    price: 279,
    mrp: 2999,
    rating: 4.6,
    reviews: 73,
    image: "showpiece",
    style: "luxury",
    room: ["home-office", "living-room"],
    material: "Marble & Brass",
    color: "White & Gold",
    size: "Set of 2",
    dimensions: "10 x 10 x 15 cm each",
    weight: "2.9 kg",
    stock: 15,
    badges: ["featured"],
    description: "Weighted marble blocks with brass edging that hold a shelf of books in line.",
    care: "Dust with a dry cloth.",
  },
  {
    name: "Ceramic Object Trio",
    category: "vases",
    subcategory: "Decorative Objects",
    price: 289,
    mrp: 2499,
    rating: 4.2,
    reviews: 61,
    image: "vase",
    style: "minimalist",
    room: ["living-room"],
    material: "Ceramic",
    color: "Ivory",
    size: "Set of 3",
    dimensions: "Various, 10-18 cm",
    weight: "1.6 kg",
    stock: 23,
    badges: [],
    description: "Three small ceramic forms in graduated heights — styling made simple.",
    care: "Hand wipe.",
  },
  {
    name: "Sculptural Wall Art in Sandstone",
    category: "wall-decor",
    subcategory: "Sculptural Wall Art",
    price: 299,
    mrp: 6499,
    rating: 4.7,
    reviews: 49,
    image: "img10",
    style: "contemporary",
    room: ["living-room", "entryway"],
    material: "Cast Sandstone",
    color: "Sand",
    size: "Large",
    dimensions: "70 x 50 x 6 cm",
    weight: "6.2 kg",
    stock: 5,
    badges: ["new", "featured"],
    description: "A relief panel cast in sandstone that reads as sculpture and hangs like art.",
    care: "Dust with a soft brush.",
  },
  {
    name: "Minimal Line Art Canvas",
    category: "posters",
    subcategory: "Minimal Art",
    price: 259,
    mrp: 2899,
    rating: 4.4,
    reviews: 133,
    image: "poster",
    style: "minimalist",
    room: ["bedroom", "home-office"],
    material: "Canvas, Oak Frame",
    color: "Ivory",
    size: "Medium",
    dimensions: "40 x 60 x 3 cm",
    weight: "1.8 kg",
    stock: 28,
    badges: [],
    description: "One continuous line on raw canvas, framed in pale oak.",
    care: "Dust lightly.",
  },
  {
    name: "Antique Brass Wall Clock",
    category: "wall-decor",
    subcategory: "Vintage Clocks",
    price: 269,
    mrp: 4199,
    rating: 4.5,
    reviews: 88,
    image: "img9",
    style: "vintage",
    room: ["dining-room", "living-room"],
    material: "Metal, Glass",
    color: "Aged Brass",
    size: "Medium",
    dimensions: "36 x 36 x 5 cm",
    weight: "1.9 kg",
    stock: 13,
    badges: [],
    description: "A gently aged brass rim with a cream dial and elegant serif numerals.",
    care: "Dust with a dry cloth.",
  },
  {
    name: "Terracotta Textured Planter",
    category: "plants-planters",
    subcategory: "Planters",
    price: 279,
    mrp: 1199,
    rating: 4.2,
    reviews: 112,
    image: "planter",
    style: "boho",
    room: ["balcony", "bathroom"],
    material: "Terracotta",
    color: "Terracotta",
    size: "Small",
    dimensions: "14 x 14 x 14 cm",
    weight: "0.9 kg",
    stock: 47,
    badges: [],
    description: "Ribbed terracotta with a raw unglazed finish that ages beautifully outdoors.",
    care: "Rinse before repotting.",
  },
  {
    name: "Framed Botanical Set of 3",
    category: "posters",
    subcategory: "Framed Sets",
    price: 289,
    mrp: 3499,
    rating: 4.6,
    reviews: 152,
    image: "poster",
    style: "scandinavian",
    room: ["bedroom", "home-office"],
    material: "Art Paper, Oak Frames",
    color: "Beige",
    size: "Set of 3 (A4)",
    dimensions: "21 x 30 cm each",
    weight: "2.4 kg",
    stock: 20,
    badges: ["bestseller"],
    description: "A curated trio of botanical studies, framed and ready to hang as a set.",
    care: "Keep away from damp walls.",
  },
  {
    name: "Statement Sculpture on Marble Base",
    category: "sculptures",
    subcategory: "Statement Sculpture",
    price: 299,
    mrp: 11999,
    rating: 4.9,
    reviews: 37,
    image: "bannerStatement",
    style: "luxury",
    room: ["entryway", "living-room"],
    material: "Bronze Finish Resin, Marble",
    color: "Bronze & White",
    size: "Extra Large",
    dimensions: "30 x 20 x 55 cm",
    weight: "8.6 kg",
    stock: 3,
    badges: ["featured", "new"],
    description:
      "An unmistakably sculptural piece on a solid marble plinth — built to hold the centre of an entryway.",
    care: "Dust with a dry cloth. Two-person lift.",
  },
  {
    name: "Wooden Mandala Wall Panel",
    category: "wall-decor",
    subcategory: "Wood Panels",
    price: 259,
    mrp: 3199,
    rating: 4.5,
    reviews: 176,
    image: "img7",
    style: "vintage",
    room: ["living-room", "entryway"],
    material: "MDF with Wood Veneer",
    color: "Honey Brown",
    size: "Medium",
    dimensions: "45 x 45 x 3 cm",
    weight: "2.2 kg",
    stock: 25,
    badges: [],
    description: "A finely cut mandala in warm veneer that throws lovely shadow in evening light.",
    care: "Dust with a soft brush.",
  },
];

export const PRODUCTS: Product[] = seeds.map((s, i) => ({
  ...s,
  id: `p-${String(i + 1).padStart(3, "0")}`,
  slug: slugify(s.name),
  gallery: s.gallery ?? [s.image, "roomLiving", "roomBedroom"],
}));

export const formatINR = (n: number) =>
  "₹" + n.toLocaleString("en-IN", { maximumFractionDigits: 0 });

export const discountPct = (p: Pick<Product, "price" | "mrp">) =>
  p.mrp > p.price ? Math.round(((p.mrp - p.price) / p.mrp) * 100) : 0;

export const getProduct = (slug: string) => PRODUCTS.find((p) => p.slug === slug);
export const getCategory = (slug: string) => CATEGORIES.find((c) => c.slug === slug);

export const productsInCollection = (slug: string): Product[] => {
  switch (slug) {
    case "under-999":
      return PRODUCTS.filter((p) => p.price < 1000);
    case "luxury-decor":
      return PRODUCTS.filter((p) => p.style === "luxury");
    case "minimalist":
      return PRODUCTS.filter((p) => p.style === "minimalist");
    case "new-home":
      return PRODUCTS.filter((p) =>
        ["mirrors", "wall-clocks", "vases", "plants-planters", "table-decor"].includes(p.category),
      );
    case "trending-now":
      return PRODUCTS.filter((p) => p.reviews > 130);
    case "gift-ideas":
      return PRODUCTS.filter((p) => p.price >= 800 && p.price <= 2600);
    case "statement-pieces":
      return PRODUCTS.filter((p) => p.price >= 3200);
    case "small-decor":
      return PRODUCTS.filter((p) => p.size.toLowerCase().includes("small"));
    case "bestsellers":
      return PRODUCTS.filter((p) => p.badges.includes("bestseller"));
    case "new-arrivals":
      return PRODUCTS.filter((p) => p.badges.includes("new"));
    default:
      return PRODUCTS;
  }
};

export const searchProducts = (q: string, limit = 8): Product[] => {
  const term = q.trim().toLowerCase();
  if (!term) return [];
  return PRODUCTS.filter((p) =>
    [p.name, p.category, p.subcategory, p.style, p.material, p.color, ...p.room]
      .join(" ")
      .toLowerCase()
      .includes(term),
  ).slice(0, limit);
};

export const relatedProducts = (p: Product, limit = 4) =>
  PRODUCTS.filter((x) => x.id !== p.id && (x.category === p.category || x.style === p.style)).slice(
    0,
    limit,
  );

export const completeTheLook = (p: Product, limit = 4) =>
  PRODUCTS.filter((x) => x.id !== p.id && x.category !== p.category && x.room.some((r) => p.room.includes(r))).slice(
    0,
    limit,
  );

export const FILTER_OPTIONS = {
  price: [
    { label: "₹0 – ₹500", min: 0, max: 500 },
    { label: "₹500 – ₹1,000", min: 500, max: 1000 },
    { label: "₹1,000 – ₹2,500", min: 1000, max: 2500 },
    { label: "₹2,500 – ₹5,000", min: 2500, max: 5000 },
    { label: "₹5,000+", min: 5000, max: Infinity },
  ],
  styles: STYLES.map((s) => s.tag),
  rooms: ROOMS.map((r) => r.slug),
  materials: Array.from(new Set(PRODUCTS.map((p) => p.material))).sort(),
  colors: Array.from(new Set(PRODUCTS.map((p) => p.color))).sort(),
  sizes: Array.from(new Set(PRODUCTS.map((p) => p.size))).sort(),
};
